<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8" />
	<title>Error Boundaries</title>
	<script src="https://cdn.staticfile.org/react/16.4.0/umd/react.development.js"></script>
	<script src="https://cdn.staticfile.org/react-dom/16.4.0/umd/react-dom.development.js"></script>
	<script src="https://cdn.staticfile.org/babel-standalone/6.26.0/babel.min.js"></script>
</head>

<body>

  <div id="root"></div>
  <script type="text/babel">
  //一个类组件变成一个错误边界。如果它定义了生命周期方法 static getDerivedStateFromError()或者componentDidCatch()中的任意一个或两个。
  //当一个错误被扔出后，使用static getDerivedStateFromError()渲染一个退路UI。使用componentDidCatch()去记录错误信息
  // class ErrorBoundary extends React.Component{
  //   constructor(props){
  //     super(props);
  //     this.state = {hasError:false};
  //   }
  //   static getDerivedStateFromError(error){
  //     return { hasError:true};
  //   }
  //   componentDidCatch(erro,info){
  //     logErrorToMyService(erro,info);
  //   }
  //   render(){
  //     if(this.state.hasError){
  //       return <h1>Something went wrong.</h1>
  //     }
  //     return this.props.children;
  //   }
  // }
  // ReactDOM.render(
  //   <ErrorBoundary>
  //     <span>hello</span>
  //     <span>world</span>
  //   </ErrorBoundary>,
  //   document.getElementById('root')
  // )

  class ErrorBoundary extends React.Component{
    constructor(props){
      super(props);
      this.state ={error:null,errorInfo:null}
    }
    componentDidCatch(error,errorInfo){
      this.setState({error:error,errorInfo:errorInfo})
    }
    render(){
      if(this.state.errorInfo){
        return(
          <div>
            <h2>Something went wrong.</h2>
            <details style={{whiteSpace: 'pre-wrap'}}>
              {this.state.error && this.state.error.toString()}
              <br/>
              {this.state.errorInfo.componentStack}
            </details>
          </div>
        );
      }
      return this.props.children;
    }
  }
  class BuggyCounter extends React.Component{
    constructor(props){
      super(props);
      this.state = {counter:0}
      this.handleClick = this.handleClick.bind(this); 
    }
    handleClick(){
      this.setState(({counter}) => ({
        counter:counter + 1
      }));
    }
    render(){
      if(this.state.counter === 5){
        throw new Error('I crashed!');
      }
      return <h1 onClick={this.handleClick}>{this.state.counter}</h1>
    }
  }
  function App(){
    return(
      <div>
        <p>
          <b>
            This is an example of error boundaries in React 16.
            <br /><br />
            Click on the numbers to increase the counters.
            <br />
            The counter is programmed to throw when it reaches 5. This simulates a JavaScript error in a component.
          </b>
        </p>
        <hr />
        <ErrorBoundary>
          <p>These two counters are inside the same error boundary. If one crashes, the error boundary will replace both of them.</p>
          <BuggyCounter />
          <BuggyCounter />
        </ErrorBoundary>
        <hr />
        <p>These two counters are each inside of their own error boundary. So if one crashes, the other is not affected.</p>
        <ErrorBoundary><BuggyCounter /></ErrorBoundary>
        <ErrorBoundary><BuggyCounter /></ErrorBoundary>
      </div>
    );
  }
  ReactDOM.render(
    <App />,
    document.getElementById('root')
  )
	</script>

</body>

</html>